### PR TITLE
feat: prefer esbuild over vite

### PR DESCRIPTION
**Pull request by manzt**
Replaces Vite with simple esbuild, using anywidget's built-in HMR.

```sh
npm run dev
```

```sh
jupyter lab
```

### CODE REVIEW

**Review by kolibril13 — APPROVED** [review]
Awesome!
Thank you so much for this contribution.
Works out of the box. 🎉 
Note that I added one additional commit in order to update the widget content anytime the model changes from the python side (as mentioned in https://github.com/manzt/anywidget/issues/185#issuecomment-1640418116)

image

You're welcome to merge this pr, or add other commits if you want

**Comment by manzt** [comment]
Cool, I just pushed a change that adds a general purpose `useModelState` hook. This exposes a similar API to `React.useState` in your React code, but will also sync the values back to python via the backbone model. 

```javascript
export default function Button() {
  let [value, setValue] = useModelState("value");
  return <button onClick={() => setValue(value + 1)} >count is {value}</button>
}
```

**Comment by manzt** [comment]
Maybe we could add a package to anywidget like `@anywidget/react` that lets does this boilerplate for you:

```javascript
import * as React from "react";
import { createRender, useModelState } from "@anywidget/react";

function Button() {
  let [value, setValue] = useModelState("value");
  return <button onClick={() => setValue(value + 1)} >count is {value}</button>
}

export let render = createRender(Button);
```

any thoughts?

**Comment by kolibril13** [comment]
> Maybe we could add a package to anywidget like `@anywidget/react` that lets does this boilerplate for you:
> 
> ```js
> import * as React from "react";
> import { createRender, useModelState } from "@anywidget/react";
> 
> function Button() {
>   let [value, setValue] = useModelState("value");
>   return <button onClick={() => setValue(value + 1)} >count is {value}</button>
> }
> 
> export let render = createRender(Button);
> ```
> 
> any thoughts?

looks neat, but I don't have enough react knowledge yet to judge if this is a good pattern or not, maybe we can discuss that in a seperate issue on the anywidget repo.

**Comment by manzt** [comment]
> just tested the latest version and ran into this bug.

I am not able to reproduce this in either Jupyter Lab or VS Code. What is your editor envrionment?

> Let's say I don't only want to have the widget class QRCodeWidget, but a second one called QRCodeWidgetBlue.

In this case, I'd use another trait for the color.

```javascript
export default function App() {
  let [content] = useModelState("content");
  let [color] = useModelState("color");
  return <QRCode value={content} fgColor={color} />;
}
```

But you could do something like:

```javascript
// widget.jsx
import * as React from "react";
import ReactDOM from "react-dom/client";
import QRCode from "react-qr-code";

import { useModelState } from "./hooks.js";

function App() {
  let [content] = useModelState("content");
  return <QRCode value={content} />;
}

export function render({ model, el }) {
  let root = ReactDOM.createRoot(el);
  root.render(
    <React.StrictMode>
      <ModelContext.Provider value={model}>
        <App />
      </ModelContext.Provider>
    </React.StrictMode>,
  );
  return () => root.unmount();
}
```

```javascript
// widget_blue.jsx
import * as React from "react";
import ReactDOM from "react-dom/client";
import QRCode from "react-qr-code";

import { useModelState } from "./hooks.js";

function AppBlue() {
  let [content] = useModelState("content");
  return <QRCode value={content} fgColor= "blue"/>;
}

export function render({ model, el }) {
  let root = ReactDOM.createRoot(el);
  root.render(
    <React.StrictMode>
      <ModelContext.Provider value={model}>
        <App />
      </ModelContext.Provider>
    </React.StrictMode>,
  );
  return () => root.unmount();
}
```

```sh
esbuild --bundle --format=esm --outdir=qr_code_widget/static src/widget.jsx src/widget_blue.jsx --watch
```

**Comment by kolibril13** [comment]
> > just tested the latest version and ran into this bug.
> 
> I am not able to reproduce this in either Jupyter Lab or VS Code. What is your editor envrionment?

I'm on a Macbook M1, Python 3.11.4, latest VS Code. 
anywidget works fine for me in JupyterLab, no refreshment bug there.
Also, I tested
```
import ipywidgets as widgets
widgets.IntSlider(value=10)
```
in multiple environments in VSCode. 
The non-refreshing bug is there as well, so this is definitely unrelated to anywidget 🌿 
 I'll file a report to that to jupyter-vscode tomorrow.

**Comment by kolibril13** [comment]
> ```
> export default function App() {
>   let [content] = useModelState("content");
>   let [color] = useModelState("color");
>   return <QRCode value={content} fgColor={color} />;
> }
> ```
that's great, and it even works with changing value with `q.color = "yellow"` even after the widget is initialized  👍🏼 
would it be possible to make this also work with 

```
export default function App({content, color}) {
  return <QRCode value={content} fgColor={color} />;
}
```
like in ipyreact?


Regarding the two separate widgets approach: Amazing, I can confirm that works as well!
image

the anywidget/react approach looks need as well!

**Comment by manzt** [comment]
> that's great, and it even works with changing value with q.color = "yellow" even after the widget is initialized 👍🏼

Yes. The `useModelState` hooks wires up things correctly so that it looks/works just like a regular React component using `useState`, but additionally one that is synchronized with the Python model.

> would it be possible to make this also work with.

I don't think so. Doing so would require anywidget to be opinionated about transforming your code and worrying about react versions, etc. The point of anywidget is to be framework agnostic and rely on web-browser standards. `ipyreact` bakes in some of these opinions, but then you can run into issues where you want a different version of react or handling of JSX and things break.

By forcing ESM, anywidget is more future proof and framework agnositic. You need to transform your code ahead of time, but minimally.

The `@anywidget/react` approach is one that would allow lots of this boilerplate to be removed when working with react but without potentially breaking things in the future.

**Comment by kolibril13** [comment]
That's amazing, I just tested this branch a bit more, and everything works.
Thank you so much for your efforts here, this is a big contribution to the scipy ecosystem!
Note, that I've also setup a sphinx project trying to render this anywidget react frontent, and it works out of the box 🎉 
https://kolibril13.github.io/ipyreact-example-gallery/02-nb.html
image

Should I merge this pr now?

**Comment by manzt** [comment]
go for it!

**Pull request merged**
